import Footer from "./components/footer";
import Navbar from "./components/navbar";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { ContextProvider } from "@/context/Context";
import "bootstrap/dist/css/bootstrap.min.css"

export const metadata = {
  title: "ShopStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      style={{ background: "#d9d9d9" }}>
        <ContextProvider>
          <Navbar />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
