import Footer from "./components/footer";
import Navbar from "./components/navbar";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";

export const metadata = {
  title: "Testing API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/darkly/bootstrap.min.css"
        />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
      
    </html>
  );
}
